name: syncapod
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.0.0
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  flutter_secure_storage: ^3.3.3
  http: ^0.12.0+4
  flutter_html: ^0.11.1
  just_audio: ^0.1.8
  palette_generator: ^0.2.2
  marquee: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true