name: syncapod
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.0.0
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  flutter_secure_storage: ^3.3.3
  http: ^0.12.0+4
  flutter_html: ^0.11.1
  just_audio: ^0.1.8
  audio_service: ^0.8.0
  palette_generator: ^0.2.2
  marquee: ^1.3.1
  url_launcher: ^5.4.5
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
  uses-material-design: true